name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: cypress/browsers:node16.14.0-chrome100-ff99
        options: --health-cmd "exit 0" --health-interval 5s --health-timeout 2s --health-retries 3
        ports:
          - 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Especifique a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run  # Certifique-se de ter esse script no seu package.json
